---
- name: ssl mkdir ---> {{ domain }}
  file: path={{ item }} state=directory
  with_items:
      - '/root/.acme.sh/{{ project }}'
      - '/opt/ssl/{{ project }}'

- name: ssl touch ---> {{ domain }}
  file: path={{ item }} state=touch
  with_items:
      - '/root/.acme.sh/{{ project }}/{{ project }}.cer'
      - '/root/.acme.sh/{{ project }}/{{ project }}.key'
      - '/root/.acme.sh/{{ project }}/fullchain.cer'

- name: ssl for ---> {{ domain }}
  shell:  curl https://get.acme.sh | 
          /root/.acme.sh/acme.sh --install-cert -d  {{ project }} \
          --cert-file /opt/ssl/{{ project }}/cert.pem \
          --key-file /opt/ssl/{{ project }}/key.pem \
          --fullchain-file /opt/ssl/{{ project }}/fullchain.pem \
#          --reloadcmd "docker exec dockerfile_nginx_1 bash -c \"service nginx reload\""
