version: '2'
services:
  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - '/opt/web:/opt/web'
      - '/opt/log:/opt/log'
      - '/etc/fb:/etc/fb'
    restart: always
    networks:
        - frontend
    depends_on:
        - php
    ports:
      - 80:80
      - 443:443
  php:
    build: ./php
    container_name: php
    volumes:
      - '/opt/web:/opt/web'
      - '/opt/log:/opt/log'
    restart: always
    networks:
      - frontend
      - backend
  mysql:
    build: ./mysql/5.6/file
    container_name: mysql
    volumes:
      - '/opt/data/mysql:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    networks:
      - backend
    ports:
      - 3306:3306
  # node:
  #     build: ./node
  #     container_name: node
  #     volumes:
  #       - '/opt/web:/opt/web'
  #     restart: always

networks:
  frontend:
  backend:


