---
- hosts: test
  vars:

  roles:
    - { role: yum, app: ["git", "curl", "python-pip"], tags: ["software"] }
    - { role: docker, tags: ["docker"] }

    - {
        role: git, # git参照 roles 下面的 git
        tags: ["git.devops"], # tag，playbook 执行的时候需要，可以打多个tag，用逗号隔开
        project_name: "devops", #项目名
        repository: "git@github.com:jackysong/docker_lnmp_swoole_efk_java.git", # 这边改成你自己的 git 地址
        dest_path: "/opt/web/devops", # 服务器上目录
        branch: "master", # git所在分支
      }


    - {
        role: templates,
        tags: ["nginx", "nginx.union"],
        file: sites-enabled/vue.conf.j2,
        path: "/opt/web/devops/dockerFile/nginx/sites-enabled/test.xx.com.conf",
        nginx_domain: "test.xx.com",
        nginx_path: "/opt/web/test",
      }

  tasks:
    - name: restartnginx
      shell: cd /opt/web/devops/dockerFile && docker-compose up -d --build nginx
      tags:
        - restartnginx
