---
- hosts: hz-test
  vars:

  roles:
    - { role: yum, app: ["git", "curl", "python-pip"], tags: ["software"] }
    - { role: docker, tags: ["docker"] }

    - {
        role: git,
        tags: ["git.devops"],
        project_name: "devops",
        repository: "ssh://gogs@gogs.68wx.com:9336/hzkt/devops.git",
        dest_path: "/opt/web/devops",
        branch: "master",
      }

    - {
        role: templates,
        tags: ["nginx", "nginx.hzy-api"],
        file: sites-enabled/hzy-api.conf.j2,
        path: "/opt/web/devops/dockerFile/nginx/sites-enabled/hzyv2-api.ztiku.com.conf",
        nginx_domain: "hzyv2-api.ztiku.com",
        backend_server1: "172.16.101.179:8080",
      }

    - {
        role: templates,
        tags: ["nginx", "nginx.api.https"],
        file: sites-enabled/api.https.conf.j2,
        path: "/opt/web/devops/dockerFile/nginx/sites-enabled/test.api.68wx.com.https.conf",
        nginx_domain: "test.api.68wx.com",
        backend_server1: "172.16.101.179",
        backend_server2: "172.16.101.179",
        ssl_path_pem: "/opt/web/ssl/test.api.68wx.com/fullchain.pem",
        ssl_path_key: "/opt/web/ssl/test.api.68wx.com/key.pem",
        nginx_static_path: "/opt/web/verifyFile/"
      }

    - {
        role: templates,
        tags: ["nginx", "nginx.api"],
        file: sites-enabled/api.conf.j2,
        path: "/opt/web/devops/dockerFile/nginx/sites-enabled/test.api.68wx.com.conf",
        nginx_domain: "test.api.68wx.com test.api.hzjy.com",
        backend_server1: "172.16.101.179",
        backend_server2: "172.16.101.179",
      }

    - {
        role: templates,
        tags: ["nginx", "nginx.yh.api","nginx.yh"],
        file: sites-enabled/yh-api.conf.j2,
        path: "/opt/web/devops/dockerFile/nginx/sites-enabled/test.yhapi.68wx.com.conf",
        nginx_domain: "test.yhapi.68wx.com",
        backend_server1: "172.16.101.179",
        backend_server2: "172.16.101.179",
    }

    - {
        role: templates,
        tags: ["nginx", "nginx.spec"],
        file: sites-enabled/static.conf.j2,
        path: "/opt/web/devops/dockerFile/nginx/sites-enabled/spec.68wx.com.conf",
        nginx_domain: "spec.68wx.com",
        nginx_path: "/opt/web/spec"
      }

    - {
        role: templates,
        tags: ["nginx", "nginx.hzyv2"],
        file: sites-enabled/vue.conf.j2,
        path: "/opt/web/devops/dockerFile/nginx/sites-enabled/hzy_v2.conf",
        nginx_domain: "hzyv2.ztiku.com",
        nginx_path: "/opt/web/agency",
      }

    - {
        role: templates,
        tags: ["nginx", "nginx.hzy", "nginx.hzy-vue"],
        file: sites-enabled/vue.conf.j2,
        path: "/opt/web/devops/dockerFile/nginx/sites-enabled/test.hzy.68wx.com.conf",
        nginx_domain: "test.hzy.68wx.com",
        nginx_path: "/opt/web/hzy-vue",
      }

    - {
        role: templates,
        tags: ["nginx", "nginx.hzy", "nginx.hzy-vue-api"],
        file: sites-enabled/hzy-new-api.conf.j2,
        path: "/opt/web/devops/dockerFile/nginx/sites-enabled/test.hzy-vue.api.ztiku.com.conf",
        nginx_domain: "test.api.hzy.68wx.com",
        backend_hzy_gateway: "172.16.101.179:9999",
      }

    - {
        role: templates,
        tags: ["nginx", "nginx.hzy", "nginx.nacos"],
        file: sites-enabled/proxy.conf.j2,
        path: "/opt/web/devops/dockerFile/nginx/sites-enabled/test.nacos.68wx.com.conf",
        nginx_domain: "test.nacos.68wx.com",
        backend_proxy: "backend_nacos",
        backend_server: "172.16.101.179:8848",
      }

    - {
        role: templates,
        tags: ["nginx", "nginx.h5.https"],
        file: sites-enabled/vue.https.conf.j2,
        path: "/opt/web/devops/dockerFile/nginx/sites-enabled/test.h5.68wx.com.https.conf",
        nginx_domain: "*.test.h5.68wx.com",
        nginx_path: "/opt/web/agentSchool-h5",
        ssl_path_pem: "/opt/web/ssl/test.h5.68wx.com/fullchain.pem",
        ssl_path_key: "/opt/web/ssl/test.h5.68wx.com/key.pem",
      }


    - {
        role: templates,
        tags: ["nginx", "nginx.h5"],
        file: sites-enabled/vue.conf.j2,
        path: "/opt/web/devops/dockerFile/nginx/sites-enabled/test.h5.68wx.com.conf",
        nginx_domain: "*.test.h5.68wx.com test.h5.68wx.com",
        nginx_path: "/opt/web/agentSchool-h5",
      }

    - {
        role: templates,
        tags: ["nginx", "nginx.union"],
        file: sites-enabled/vue.conf.j2,
        path: "/opt/web/devops/dockerFile/nginx/sites-enabled/test.union.68wx.com.conf",
        nginx_domain: "test.union.68wx.com",
        nginx_path: "/opt/web/agency",
      }

    - {
        role: templates,
        tags: ["nginx", "nginx.admin"],
        file: sites-enabled/vue.conf.j2,
        path: "/opt/web/devops/dockerFile/nginx/sites-enabled/test.admin2.68wx.com.conf",
        nginx_domain: "test.admin2.68wx.com",
        nginx_path: "/opt/web/tkwx",
        backend_server1: "172.16.101.179",
        backend_server2: "172.16.101.179",
      }

    - {
        role: templates,
        tags: ["nginx", "nginx.yh.union","nginx.yh"],
        file: sites-enabled/vue.conf.j2,
        path: "/opt/web/devops/dockerFile/nginx/sites-enabled/test.union.luohu8.com.conf",
        nginx_domain: "test.yhunion.68wx.com",
        nginx_path: "/opt/web/yh-agency-new",
       }

    - {
        role: templates,
        tags: ["nginx", "nginx.yh.admin","nginx.yh"],
        file: sites-enabled/vue.conf.j2,
        path: "/opt/web/devops/dockerFile/nginx/sites-enabled/test.admin.luohu8.com.conf",
        nginx_domain: "test.yhadmin.68wx.com",
        nginx_path: "/opt/web/yh-tkwx-new",
        backend_server1: "172.16.101.179",
        backend_server2: "172.16.101.179",
    }


    - {
        role: templates,
        tags: ["nginx", "nginx.goproxy"],
        file: sites-enabled/goproxy.admin.conf.j2,
        path: "/opt/web/devops/dockerFile/nginx/sites-enabled/goproxy.conf",
        nginx_domain: "goproxy.admin.68wx.com",
        backend_server1: "172.16.101.179:32080",
      }

    - {
        role: templates,
        tags: ["nginx", "nginx.jenkins"],
        file: sites-enabled/jenkins.conf.j2,
        path: "/opt/web/devops/dockerFile/nginx/sites-enabled/ci.68wx.com.conf",
        nginx_jenkins_ip: "172.16.101.179:49000",
        nginx_jenkins_server: "ci.68wx.com",
        nginx_jenkins_alias: "jenkins_server",
      }

    - {
        role: templates,
        tags: ["nginx", "nginx.saas"],
        file: sites-enabled/saas.conf.j2,
        path: "/opt/web/devops/dockerFile/nginx/sites-enabled/saas.conf",
        nginx_domain: "_",
        nginx_path: "/opt/web/xtkwx/student/",
        nginx_static_path: "/opt/web/xtkwx/student/static/",
        backend_server1: "172.16.101.179",
        backend_server2: "172.16.101.179",
        nginx_api_domain: "test.api.68wx.com",
      }

    - {
        role: templates,
        tags: ["nginx", "nginx.saas.https"],
        file: sites-enabled/saas.https.conf.j2,
        path: "/opt/web/devops/dockerFile/nginx/sites-enabled/saas.https.conf",
        nginx_domain: "test.tiku.68wx.com",
        nginx_path: "/opt/web/xtkwx/student/",
        nginx_static_path: "/opt/web/xtkwx/student/static/",
        nginx_api_domain: "test.api.68wx.com",
        ssl_path_pem: "/opt/web/ssl/test.tiku.68wx.com/fullchain.pem",
        ssl_path_key: "/opt/web/ssl/test.tiku.68wx.com/key.pem",
      }

    - {
        role: templates,
        tags: ["config.tomcat"],
        file: tomcat/server.xml,
        path: "/mnt/apache-tomcat-8.0.53/conf/server.xml",
      }

    - {
        role: templates,
        tags: ["config.hzy", "config.hzy.system"],
        file: hzy/system/application.yml.j2,
        path: "/opt/hzy/jeecg-boot-module-system/src/main/resources/application.yml",
        profile: "test",
      }

    - {
        role: templates,
        tags: ["config.hzy", "config.hzy.system"],
        file: hzy/system/bootstrap.yml.j2,
        path: "/opt/hzy/jeecg-boot-module-system/src/main/resources/bootstrap.yml",
        server_addr: "172.16.101.179:8848",
        heart_beat_interval: "5000",
        profile: "test",
        application_name: "jeecg-system",
        boot_port: "7001",
      }

    - {
        role: templates,
        tags: ["config.hzy", "config.hzy.demo"],
        file: hzy/demo/application.yml.j2,
        path: "/opt/hzy/jeecg-boot-module-demo/src/main/resources/application.yml",
        profile: "test",
      }

    - {
        role: templates,
        tags: ["config.hzy", "config.hzy.demo"],
        file: hzy/demo/bootstrap.yml.j2,
        path: "/opt/hzy/jeecg-boot-module-demo/src/main/resources/bootstrap.yml",
        server_addr: "172.16.101.179:8848",
        heart_beat_interval: "5000",
        profile: "test",
        application_name: "jeecg-demo",
        boot_port: "7002",
      }

    - {
        role: templates,
        tags: ["config.hzy", "config.hzy.gateway"],
        file: hzy/gateway/bootstrap.yml.j2,
        path: "/opt/hzy/jeecg-cloud-module/jeecg-cloud-gateway/src/main/resources/bootstrap.yml",
        server_addr: "172.16.101.179:8848",
        heart_beat_interval: "5000",
        profile: "test",
        application_name: "jeecg-cloud-gateway",
        boot_port: "9999",
      }

    - {
        role: templates,
        tags: ["config.tkwx"],
        file: tkwx-admin/application.yml.j2,
        path: "/opt/tkwx/admin/src/main/resources/application.yml",
        profile: "test",
      }

    - {
        role: templates,
        tags: ["config.tkwx"],
        file: tkwx-admin/bootstrap.yml.j2,
        path: "/opt/tkwx/admin/src/main/resources/bootstrap.yml",
        server_addr: "172.16.101.179:8848",
        heart_beat_interval: "5000",
        profile: "test",
        application_name: "tkwx-admin",
        boot_port: "8888",
      }


    - {
        role: templates,
        tags: ["config.tkwx"],
        file: tkwx-api/application.yml.j2,
        path: "/opt/tkwx/api/src/main/resources/application.yml",
        profile: "test",
      }


    - {
        role: templates,
        tags: ["config.agent_school"],
        file: agent_school/nuxt.config.js.j2,
        path: "/opt/web/agentSchool/nuxt.config.js",
        nginx_domain: "http://test.api.68wx.com/",
      }
    - {
        role: templates,
        tags: ["config.yh_agency_school"],
        file: agent_school/nuxt.yh.config.js.j2,
        path: "/opt/web/yh-agencySchool/nuxt.yh.config.js",
        nginx_domain: "http://test.yhapi.68wx.com/",
    }

    - {
        role: templates,
        tags: ["nginx", "nginx.hzy-vue.h5"],
        file: sites-enabled/vue.conf.j2,
        path: "/opt/web/devops/dockerFile/nginx/sites-enabled/h5.hzy.68wx.com.conf",
        nginx_domain: "test.h5.hzy.68wx.com",
        nginx_path: "/opt/web/h5live_new",
      }

    # - {
    #     role: templates,
    #     tags: ["config.hzy", "config.hzy.seata"],
    #     file: hzy/seata/file.conf.j2,
    #     path: "/opt/hzy/jeecg-boot-module-demo/src/main/resources/file.conf",
    #     db_address: "rm-bp1v157qgn56b88wa.mysql.rds.aliyuncs.com:3306/seata",
    #     db_user: "hzyonline",
    #     db_pwd: "3329!ccc2kldfu78",
    #   }

    # - {
    #     role: templates,
    #     tags: ["config.hzy", "config.hzy.seata"],
    #     file: hzy/seata/registry.conf.j2,
    #     path: "/opt/hzy/jeecg-boot-module-demo/src/main/resources/registry.conf",
    #     nacos_addr: "172.16.101.179:8848",
    #     nacos_user: "nacos",
    #     nacos_pwd: "nacos",
    #   }

    # - {
    #     role: templates,
    #     tags: ["config.hzy", "config.hzy.seata"],
    #     file: hzy/seata/file.conf.j2,
    #     path: "/opt/hzy/jeecg-boot-module-system/src/main/resources/file.conf",
    #     db_address: "rm-bp1v157qgn56b88wa.mysql.rds.aliyuncs.com:3306/seata",
    #     db_user: "hzyonline",
    #     db_pwd: "3329!ccc2kldfu78",
    #   }

    # - {
    #     role: templates,
    #     tags: ["config.hzy", "config.hzy.seata"],
    #     file: hzy/seata/registry.conf.j2,
    #     path: "/opt/hzy/jeecg-boot-module-system/src/main/resources/registry.conf",
    #     nacos_addr: "172.16.101.179:8848",
    #     nacos_user: "nacos",
    #     nacos_pwd: "nacos",
    #   }

  tasks:
    - name: restartnginx
      shell: cd /opt/web/devops/dockerFile && docker-compose up -d --build nginx
      tags:
        - restartnginx
